name: Deploy on PROD environment

on:
  pull_request:
    types: [closed]
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  deploy:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore src/Golub.sln

      - name: Build
        run: dotnet build --no-restore --configuration Release src/Golub.sln

      - name: Publish
        run: dotnet publish --configuration Release --framework net9.0 --runtime linux-x64 --self-contained false -o publish_output src/Golub.sln

      - name: List files for debugging
        run: ls -R publish_output

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.CONTABO_SERVER_SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: ssh-keyscan -H ${{ secrets.CONTABO_SERVER_SSH_SERVER_IP }} >> ~/.ssh/known_hosts
      
      - name: Stop service on server
        run: ssh ${{ secrets.CONTABO_SERVER_SSH_USER }}@${{ secrets.CONTABO_SERVER_SSH_SERVER_IP }} "sudo systemctl stop golub.service"

      - name: Clean files on destination (excluding folders and appsettings.json)
        run: |
          ssh ${{ secrets.CONTABO_SERVER_SSH_USER }}@${{ secrets.CONTABO_SERVER_SSH_SERVER_IP }} \
            "find /var/www/api/golub/ -type f ! -name 'appsettings.json' -exec rm -f {} +"

      - name: Copy files via rsync
        run: |
          rsync -avz --exclude 'appsettings.json' ./publish_output/ ${{ secrets.CONTABO_SERVER_SSH_USER }}@${{ secrets.CONTABO_SERVER_SSH_SERVER_IP }}:${{ secrets.CONTABO_SERVER_SSH_QA_DESTINATION_PATH }}

      - name: Change ownership to www-data
        run: |
          ssh ${{ secrets.CONTABO_SERVER_SSH_USER }}@${{ secrets.CONTABO_SERVER_SSH_SERVER_IP }} "sudo chown -R www-data:www-data /var/www/api/golub/"

      - name: Set permissions for directories to 755
        run: |
            ssh ${{ secrets.CONTABO_SERVER_SSH_USER }}@${{ secrets.CONTABO_SERVER_SSH_SERVER_IP }} "sudo find /var/www/api/golub/ -type d -exec chmod 755 {} \;"
            
      - name: Set permissions for files to 644
        run: |
            ssh ${{ secrets.CONTABO_SERVER_SSH_USER }}@${{ secrets.CONTABO_SERVER_SSH_SERVER_IP }} "sudo find /var/www/api/golub/ -type f -exec chmod 644 {} \;"
       
      - name: Start service on server
        run: ssh ${{ secrets.CONTABO_SERVER_SSH_USER }}@${{ secrets.CONTABO_SERVER_SSH_SERVER_IP }} "sudo systemctl start golub.service"