name: Deploy on PROD environment

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    types: [closed]
    branches:
      - dev
      - main
  workflow_dispatch:

env:
  SERVICE_NAME: api.golub.service
  DEPLOYMENT_PATH: /var/www/api/golub/

jobs:
  deploy:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: Build with restore
        run: dotnet build --configuration Release src/Golub.sln

      - name: Publish
        run: dotnet publish --configuration Release --framework net9.0 --runtime linux-x64 --self-contained false -o publish_output src/Golub.sln

      - name: List files for debugging
        run: ls -R publish_output

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.CONTABO_SERVER_SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: ssh-keyscan -H ${{ secrets.CONTABO_SERVER_SSH_SERVER_IP }} >> ~/.ssh/known_hosts
      
      - name: Stop service on server
        run: |
          ssh ${{ secrets.CONTABO_SERVER_SSH_USER }}@${{ secrets.CONTABO_SERVER_SSH_SERVER_IP }} \
          "sudo systemctl stop ${{ env.SERVICE_NAME }}"
  
      - name: Clean files on destination (excluding folders and specific files/folders)
        run: |
          EXCLUDED_ITEMS=('appsettings.json') # Niz fajlova i foldera za preskakanje
          EXCLUDED_ARGS=$(printf " ! -name '%s' ! -path '*/%s/*'" "${EXCLUDED_ITEMS[@]}" | sed 's/  */ /g') # Kreira string za find
          ssh ${{ secrets.CONTABO_SERVER_SSH_USER }}@${{ secrets.CONTABO_SERVER_SSH_SERVER_IP }} \
            "find ${{ env.DEPLOY_PATH }} -type f $EXCLUDED_ARGS -exec rm -f {} +"
      
      - name: Copy files via rsync
        run: |
          rsync -avz --exclude 'appsettings.json' ./publish_output/ ${{ secrets.CONTABO_SERVER_SSH_USER }}@${{ secrets.CONTABO_SERVER_SSH_SERVER_IP }}:${{ env.DEPLOY_PATH }}

      - name: Set permissions for directories to 755
        run: |
          ssh ${{ secrets.CONTABO_SERVER_SSH_USER }}@${{ secrets.CONTABO_SERVER_SSH_SERVER_IP }} "sudo find ${{ env.DEPLOY_PATH }} -type d -exec chmod 755 {} \;"

      - name: Set permissions for files to 644
        run: |
          ssh ${{ secrets.CONTABO_SERVER_SSH_USER }}@${{ secrets.CONTABO_SERVER_SSH_SERVER_IP }} "sudo find ${{ env.DEPLOY_PATH }} -type f -exec chmod 644 {} \;"

      - name: Start hrms.qa.service
        run: ssh ${{ secrets.CONTABO_SERVER_SSH_USER }}@${{ secrets.CONTABO_SERVER_SSH_SERVER_IP }} "sudo systemctl start ${{ env.SERVICE_NAME }}"